### PR TITLE
Rebased conversions of more files

### PR DESCRIPTION
**Pull request by stephenh**

### CODE REVIEW

**Comment by anovstrup** [comment]
The build fails when I check out f3d5bc3, but it succeeds on 3e15630.  It'll be easier to verify/review if the commits are ordered/patched in such a way that all of them build successfully.

**Comment by gkossakowski** [comment]
I skimmed diffs and left a few comments. I did it partly because I wanted to test the workflow and partly because it's a fun to see Java code translate to Scala :-)

**Comment by stephenh** [comment]
I rebased my commits to address Aaron's point that the gwtc target was broken for some commits as the JavaConversions hack was needed before I realized it.

Oddly enough, this seems to have nuked all of the line-by-line comments on the previous commits. I suppose I can see why, from an implementation perspective, github is doing what it's doing, but I like the reitveld/gerrit model of not discarding previous changesets/comments.

This may/may not be a deal breaker for github usage, but it at least insinuates that appending new commits to an open pull request (vs. rebasing them) may work better for github's collaboration model. At the expense of less clean patch series.

But I'm willing to compromise on that. If anything, appending vs. rebasing means no forced updates of master, which, even if it's just the master for my fork, I've been conditioned to not like doing.

**Comment by anovstrup** [comment]
Ok, I made some commit/line comments (pretty minor, for the most part).  Let's put the fixed versions on a _separate_ branch so that these comments don't get wiped out (until after the pull request is merged, at least).

**Comment by stephenh** [comment]
If I push the changes to a separate branch, won't I have to open a new pull request for that branch? I haven't read the link Greg posted about the github workflow, but is the idea to have a branch-per-patchset? E.g. thetopic-v1, thetopic-v2, thetopic-v3?

**Comment by anovstrup** [comment]
The guide that Greg linked to doesn't specifically address the issue of reviewing/fixing pull requests. They suggest rebasing on master _before_ issuing the pull request, but don't really talk about what happens after that.  I think there are two reasonable approaches:
- **branch-per-patchset** (as you defined it, Stephen).  I _think_ this would entail creating a new pull request, but it could (should) refer back to this one in the description.
- **append to pull request**.

I tend to prefer the first approach, since it keeps the mainline clean and makes things easier on reviewers.  However, given the nature of this repository (as sample code, rather than the primary project code), I'm willing to compromise.

I suggest that we use the "append" model when the fixes are mostly small (like those in my last few comments).  In this case, there's a commit that I'd like to see removed.  I prefer that we do this in a separate pull request, instead of appending a commit to revert the unwelcome changes.

**Comment by stephenh** [comment]
I was initially skeptical, but I could come around on branch-per-patchset (save for trivial changes, as you said), because then we could use the github compare branches feature to effectively do gerrit-style diffs-between-patchsets. I'll try that for this patch series and see how it works.

**Comment by stephenh** [comment]
Huh. Well, I tried pushing to a new branch, and making another pull request, but I'm fairly disappointed with the result.

I was hoping the compare view of the two branches:

https://github.com/stephenh/scalagwt-sample/compare/stephenh:master...stephenh:master-v2

Would only show what changed. If I do "diff origin/master origin/master-v2" on the git CLI, I get only the ~10 lines that really changed between those two trees. I'm not sure why github is not being that smart.

I know clean patch series are a great goal, but AFAICT github doesn't have a nice workflow that supports successive iterations of a patch series. Such that I'd be tempted to heavily favor the append style of revising patch series going forward.

(Unless I'm missing something?)

Closing this pull request, see #3 instead.

**Comment by stephenh** [comment]
Turns out what I'd like to see in the compare view is what "git diff master master-v2" shows, but it's currently showing the output of "git diff master...master-v2". Not entirely sure why.

**Comment by gkossakowski** [comment]
This is all plain annoying. I'll ask around to see how people use github for code reviews. I didn't check it carefully enough before move because I assumed that so popular service simply gets it right.

**Comment by anovstrup** [comment]
It _is_ a little annoying, but it was easy enough to update stephen's remote on my local machine and do the comparison there.

**Comment by gkossakowski** [comment]
The point is that code review is quite time-consuming process and we should have tools that make it as pleasant and efficient as possible. Otherwise, the whole idea of code reviews will start to fall apart, I'm afraid.

**Pull request closed without merging**
