### PR TITLE
Handlers

### PR DESCRIPTION
**Pull request by anovstrup**
Implemented convenience API for handlers

### CODE REVIEW

**Comment by anovstrup** [comment]
There are a couple design issues I want to raise here, although we don't necessarily need to address them before merging.  Long term, however, it's likely that some form of the Handlers will end up in an official GWT API, so it's worth some careful consideration.

## Rich handler overloads

In the attached implementation, the pimp-my-library pattern is used to provide convenience methods for adding handlers to widgets that receive events. For example, the `RichHasClickHandlers` class enhances the `HasClickHandlers` interface with two `onClick` methods. 

The first has the signature `def onClick(fn: ClickEvent => Unit): Unit`.  This method is useful for writing code where the event is actually used: `button onClick { event: ClickEvent => Window.alert("Click from " + event.getSource }`.

The second method, with signature `def onClick[T](body: => T): Unit`, is useful in the common case where the event is ignored: `button onClick { Window.alert("Click!") }`.

Unfortunately, the method overload makes the syntax for the first case more verbose.  We'd really like to write `button onClick { event => Window.alert("Click from " + event.getSource) }`, but the compiler cannot resolve the parameter type due to the overloaded method.

### Possible solutions
1. _Rename the methods_.  This would solve the problem by removing the overload, but it might be hard to remember which method to use (unless the name makes it perfectly clear).  If we can come up with great method names to distinguish the two use cases, this might be the best option.
2. _Remove the second method_.  This would make the syntax for the second, and, I think, more common, case slightly more verbose: `button onClick { _ => Window.alert("Click!") }`.

## Implicit imports

I factored the implicit methods into separate traits/modules to give the user some freedom over how they want to bring them into scope.  They can"
- _Import all the implicits_ with `import Handlers._`
- _Import implicits for particular event/handler types_ with, for example, `import ChangeHandlers._`
- _Mixin traits for particular event/handler types_: `class MyClass extends ChangeHandlers with ClickHandlers`

However, if the user would like to avoid importing certain (perhaps more dangerous) implicits, they can only do so by selectively importing the individual methods that they want.  For example, the user might wish to avoid importing `implicit def body2clickHandler(body: () => Unit): ClickHandler`.

With a little more refactoring, we could make it possible for the user to easily import only the `RichHas*Handlers` classes and their associated implicits, without importing the more general implicits that convert functions to `*Handlers`. Would this be worthwhile?

**Comment by anovstrup** [comment]
Hmm, this may have broken something. The BasicPopup demo may not be working.

**Comment by stephenh** [comment]
If we go with the 2nd option, and remove the no-argument overload, that may mean we don't need the RichXxx wrappers, and can do an implicit right from Function1 to ClickHandler, as the code would always, unambiguously look like a function:

```
foo onclick { _ => ... }
```

We wouldn't have the problem with { ... } being considered a block and only converting the last statement.

**Comment by anovstrup** [comment]
Closing. See #5.

**Comment by anovstrup** [comment]
Note that even with the second option, we'll need the RichHas*Handlers wrappers if we want to use, e.g., `onClick` instead of `addClickHandler`.  However, the implementation would be a lot simpler.  My question, I guess, is whether the "ignore the event" use case is common enough to justify avoiding the extra `_ =>` syntax?

**Comment by gkossakowski** [comment]
I'd strongly vote for simpler implementation which means second option. We can always refactor it if we feel it's worth it. KISS for now :-)

**Pull request closed without merging**
