### PR TITLE
Remove greetings printing.

### PR DESCRIPTION
**Pull request by gkossakowski**
They were used mainly to inform people
that compilation is really slow. It got
a lot better so we can safely remove it.

Change-Id: I231c0892d90e48f3eb6269bb67cb00c432e92b0b
Signed-off-by: Grzegorz Kossakowski grzegorz.kossakowski@gmail.com

### CODE REVIEW

**Comment by anovstrup** [comment]
Looks fine. Can we further improve compilation speed by compiling ScalaLibrary to a gwtar?

**Comment by gkossakowski** [comment]
I don't know details behind gwtar. I guess @stephenh knows more about it.

Nonetheless, we can further improve compilation speed by switching from text protobuf messages to binary ones. See scalagwt/scalagwt-gwt#23.

**Comment by stephenh** [comment]
Per the gwtar, you just invoke GWT's CompileModule class with the name of the module you want compiled. As long as you've run the scala compiler first for it to find the jribble files, it should work fine:

https://github.com/stephenh/scalagwt-scala/blob/embed/build.xml#L559

**Comment by gkossakowski** [comment]
The question is if packaging scala library as gwtar would make compilation faster.

**Comment by stephenh** [comment]
Ah, sorry. Yeah, I'm sure it would because then GWT doesn't need to parse the jribble files at all. It will only have to parse the .jribble files for the user's app itself. (My embedding spike used this and it was pretty quick--no multi-minute first compile to populate the unit cache.)

**Pull request merged**
